### ISSUE TITLE
Writing ascii with floating-point weights does not parallelize

### ISSUE THREAD

**Issue by alugowski** [GT-TDAlab/PIGO#4]
If I write an unweighted COO with `pigo::COO::write` then I see about ~650 MB/s on my laptop. However, a COO with floating-point weights, such as:
```
pigo::COO<
    uint32_t,    // class Label=uint32_t,
    uint32_t,    // class Ordinal=Label,
    uint32_t*,   // class Storage=Label*,
    false,       // bool symmetric=false,
    false,       // bool keep_upper_triangle_only=false,
    false,       // bool remove_self_loops=false,
    true,        // bool weighted=false,
    float        // class Weight=float,
>
```
sees that speed drop 10x.

I suspect that the cause is the code that writes floating-point weights: https://github.com/GT-TDAlab/PIGO/blob/370c4b441d30ba78bc880bc7ce46fff9729c91e9/include/pigo/impl/pigo.impl.hpp#L297C10-L297C21

`write_ascii` uses `std::to_string`, which is thread safe but it does not parallelize. Probably for the same reason none of the other stdlib f-to-s and s-to-f methods parallelize: locking on the locale.

**Comment by alugowski** [comment]
Suggestion: use `std::to_chars` which now has floating-point versions available in all major compilers (sometimes latest compiler versions only, though).

**Comment by kasimirgabert** [comment]
I was able to use a modified version of STB's `sprintf` (https://github.com/nothings/stb/blob/master/stb_sprintf.h), which has a friendly non-licensing structure such that it can be included in this code base easily. It also does not depend on modern compilers and C++17 features.

Overall this brings writing weighted COOs with floats, on a test file I have, from 0.245 seconds to 0.0379 seconds, which is in-line with where it likely should be.

Thanks for this great bug report!
