### ISSUE TITLE
Improving upon PIGO for dynamic graphs

### ISSUE THREAD

**Issue by wolfram77** [GT-TDAlab/PIGO#6]
Hello @kasimirgabert 

I am trying to improve upon PIGO - to design a fast dynamic graph loader, supporting some basic operations in parallel. The idea is to load the graph directly into a data structure that supports efficient queries, such as `hasEdge(u, v)`, and efficient updates, such as `addEdge(u, v, w)` or `removeEdges(u, v)`. For now, i am simply trying to load a graph in Matrix Market file format into Edgelists. Similar to PIGO, i am using `mmap()` to map the file into memory, reading the lines in parallel, and translating it into numbers with `std::from_chars()`. On the system i use (an Intel Xeon Silver 4116 CPU with 12 cores) i am able to perform PIGO graph load of `indochina-2004` graph in `2.3 - 2.4s` and PIGO graph sort in `2.4 - 2.5s`. However, the edgelists i load is taking `3.2 - 3.3s` with 24 threads.

Could you share some insights on the techniques you use to improve the performance of PIGO?

Here is code i am working on:
https://github.com/puzzlef/graph-openmp

**Comment by kasimirgabert** [comment]
Hi @wolfram77 , thanks for the interest in PIGO. There are a handful of techniques that you can use to improve performance, and I would start with profiling to understand where you are spending most of your time. I would ask a separate question back to you: can you take PIGO and modify it/embed it into your application, so that you don't need to worry about implementing this yourself? If not, what are the barriers?

**Comment by wolfram77** [comment]
Hello @kasimirgabert

I had been unaware of PIGO, and was working on a parallel dynamic graph loader since the end of 2022. 2-3 months back I came across PIGO and was able to [improve upon it](https://arxiv.org/abs/2311.14650). Interestingly, converting Edgelist to CSR is a very slow operation - it may be possible to improve this. Further, I want to load edges directly into a dynamic graph data structure (something like a CSR with holes), with memory being managed by itself. This is going to be helpful for quickly experimenting with dynamic graph algorithms.

I am a PhD research student working on dynamic graph algorithms, and loading graphs is one of the major time consuming parts.

**Comment by kasimirgabert** [comment]
Great work and I'm glad to see this! Good luck with your studies.
